### ISSUE TITLE
Move examples into ferryjs/ferry-examples repository

### ISSUE THREAD

**Issue by jfexyz** [ferryjs/ferry#10]
Just to clean the main repository up a bit, and make development a little smoother.

**Comment by jfexyz** [comment]
If this is something you want to do, here's the best way. Don't do this in your current ferry clone, rather clone a new one:
- `git clone https://github.com/ferryjs/ferry.git ferry-examples && cd ferry-examples`
- `git filter-branch --prune-empty --subdirectory-filter examples development`
- `git remote set-url origin https://github.com/ferryjs/ferry-examples.git` (Update the URL to the new repo.)
- `git push origin --force`

**Comment by desmondmorris** [comment]
+1 @joshuajabbour

**Comment by jfexyz** [comment]
[Done](https://github.com/ferryjs/ferry-examples)
